import time
from playwright.sync_api import sync_playwright

def verify():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.goto("http://localhost:4173")

        # Click on the IP (B&B) tab
        page.get_by_text("IP (B&B)").click()
        time.sleep(1)

        # Wait for the IP form to appear
        page.wait_for_selector("h2:has-text('Integer Programming')")

        # To demonstrate overflow, enter a very long solution array for c or b? No, wait,
        # The result is generated by the backend. Since the backend is not running, we can't easily get a result to display unless we mock it.
        # Let's mock the API response.
        page.route("**/api/ip", lambda route: route.fulfill(
            status=200,
            json={
                "success": True,
                "fun": 123.45,
                "x": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0],
                "tree_plot": ""
            }
        ))

        # Click Solve IP button
        page.get_by_role("button", name="Solve IP").click()

        # Wait for the result code element to appear
        page.wait_for_selector("code[aria-label='Solution code']")

        # Take screenshot
        page.screenshot(path="verification/ip_overflow.png")

        # Evaluate if the element has horizontal scroll
        is_scrollable = page.evaluate('''() => {
            const el = document.querySelector("code[aria-label='Solution code']");
            return el.scrollWidth > el.clientWidth;
        }''')

        print(f"Is scrollable: {is_scrollable}")

        browser.close()

if __name__ == "__main__":
    verify()
